import {
  Affiliation,
  AllProducts,
  Analytics,
  API,
  CloudServices,
  CustomersCom,
  Data,
  Design,
  ECommerce,
  Finance,
  Get20,
  Home,
  HumanServices,
  Legal,
  Marketing,
  NoCode,
  Productivity,
  Sales,
  SignIn,
  SignUp,
  Web,
} from "../../pages/imports";

export const menuTop = [
  { url: "/affiliation", title: "Affiliation", class: Affiliation },
  { url: "/api", title: "White Label & API", class: "API" },
  { url: "/get20", title: "Get $20", class: "Get20" },
  { url: "/signin", title: "SignIn", class: "SignIn" },
  { url: "/signup", title: "Join Secret", class: "SignUp" },
];

export const menuBottom = [
  { url: "/allProducts", title: "All Products", class: "AllProducts" },
  { url: "/analytics", title: "Analytics", class: "Analytics" },
  { url: "/data", title: "Data", class: "Data" },
  { url: "/customer", title: "Customer Communication", class: "CustomersCom" },
  { url: "/finance", title: "Finance", class: "Finance" },
  { url: "/ecommerce", title: "Ecommerce", class: "ECommerce" },
  { url: "/legal", title: "Legal", class: "Legal" },
  { url: "/cloud", title: "Cloud Services", class: "CloudServices" },
  { url: "/sales", title: "Sales", class: "Sales" },
  { url: "/humanResources", title: "Human Resources", class: "HumanServices" },
  { url: "/marketing", title: "Marketing", class: "Marketing" },
  { url: "/design", title: "Design", class: "Design" },
  { url: "/nocode", title: "NoCode", class: "NoCode" },
  { url: "/productivity", title: "Productivity", class: "Productivity" },
  { url: "/web", title: "Web Develeopment & IT", class: "Web" },
];
